openapi: 3.1.0
info:
  title: Cloud Drive API
  description: Communication between cloud drive server and its clients
  version: 0.1.0

paths:
  /auth/signup:
    post:
      summary: Register a new user.
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Registration successfull
        "409":
          description: E-mail already in use
  /auth/signin:
    post:
      summary: Log in user
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Access token
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
        "401":
          description: Bad login data

components:
  parameters:
    AccessToken:
      in: header
      name: Bearer
      required: true
      schema:
        type: string
      description: Access token